---
- hosts: local
  connection: local
  become: yes
  become_user: root
  gather_facts: no
  tasks:
   - name: add loopback
     command: ifconfig  lo:2 {{ address }} netmask 255.255.255.255 up

   - name: test loopback
     command: ping -q -c 1 -W 1 {{ address }}
     register: res
     retries: 0
     until: (" 0% packet loss" in res.stdout)
     failed_when: (" 0% packet loss" not in res.stdout)
     changed_when: no

   - name: Configure static route in the router.
     module_static:
       prefix: "{{ address }}"
       prefix_length: 32
       next_hop: "192.168.10.5"

   - name: test loopback in the router
     command: ping -q -c 1 -W 1 -I {{ address }}  192.168.10.4
     register: res
     retries: 2
     until: (" 0% packet loss" in res.stdout)
     failed_when: (" 0% packet loss" not in res.stdout)
     changed_when: no
